<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PhimSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('phim')->insert([
            [
                'ten_phim' => 'Avengers: Endgame',
                'dao_dien' => 'Anthony Russo, Joe Russo',
                'dien_vien' => 'Robert Downey Jr., Chris Evans',
                'the_loai' => 'Hành động, Viễn tưởng',
                'thoi_luong' => 181,
                'ngon_ngu' => 'en',
                'quoc_gia' => 'Mỹ',
                'ngay_khoi_chieu' => '2019-04-26',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Các Avengers hợp lực để đảo ngược hậu quả của cú búng tay định mệnh.',
                'trailer_url' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
                'anh_poster' => 'phim/avengers.jpg',
                'anh_banner' => 'phim/avengers_banner.jpg',
                'do_tuoi' => 13,
                'danh_gia' => 9.0,
                'trang_thai' => 'Ngừng chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'Godzilla x Kong: The New Empire',
                'dao_dien' => 'Adam Wingard',
                'dien_vien' => 'Rebecca Hall, Brian Tyree Henry',
                'the_loai' => 'Hành động, Khoa học viễn tưởng',
                'thoi_luong' => 115,
                'ngon_ngu' => 'vi-en',
                'quoc_gia' => 'Mỹ',
                'ngay_khoi_chieu' => '2024-03-29',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Hai quái vật huyền thoại hợp tác chống lại mối đe dọa mới từ Hollow Earth.',
                'trailer_url' => 'https://www.youtube.com/watch?v=r7DqccP1Q_4',
                'anh_poster' => 'phim/godzillaxkong.jpg',
                'anh_banner' => 'phim/godzillaxkong_banner.jpg',
                'do_tuoi' => 13,
                'danh_gia' => 8.2,
                'trang_thai' => 'Đang chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'Inside Out 2',
                'dao_dien' => 'Kelsey Mann',
                'dien_vien' => 'Amy Poehler, Maya Hawke',
                'the_loai' => 'Hoạt hình, Phiêu lưu',
                'thoi_luong' => 100,
                'ngon_ngu' => 'vi-en',
                'quoc_gia' => 'Mỹ',
                'ngay_khoi_chieu' => '2024-06-14',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Riley bước vào tuổi teen với những cảm xúc hoàn toàn mới.',
                'trailer_url' => 'https://www.youtube.com/watch?v=LEjhY15eCx0',
                'anh_poster' => 'phim/insideout2.jpg',
                'anh_banner' => 'phim/insideout2_banner.jpg',
                'do_tuoi' => 6,
                'danh_gia' => 8.7,
                'trang_thai' => 'Đang chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'Lật Mặt 7: Một Điều Ước',
                'dao_dien' => 'Lý Hải',
                'dien_vien' => 'Lý Hải, Trần Kim Hải',
                'the_loai' => 'Tâm lý, Hài hước',
                'thoi_luong' => 125,
                'ngon_ngu' => 'vi',
                'quoc_gia' => 'Việt Nam',
                'ngay_khoi_chieu' => '2024-04-26',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Câu chuyện cảm động về tình cha con và lòng hiếu thảo.',
                'trailer_url' => 'https://www.youtube.com/watch?v=sU6pFI7VYJw',
                'anh_poster' => 'phim/latmat7.jpg',
                'anh_banner' => 'phim/latmat7_banner.jpg',
                'do_tuoi' => 13,
                'danh_gia' => 7.9,
                'trang_thai' => 'Đang chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'Venom: The Last Dance',
                'dao_dien' => 'Kelly Marcel',
                'dien_vien' => 'Tom Hardy, Juno Temple',
                'the_loai' => 'Hành động, Viễn tưởng',
                'thoi_luong' => 120,
                'ngon_ngu' => 'en',
                'quoc_gia' => 'Mỹ',
                'ngay_khoi_chieu' => '2024-10-25',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Eddie Brock đối mặt với kẻ thù cuối cùng của Venom.',
                'trailer_url' => 'https://www.youtube.com/watch?v=6xmjBmcTq0c',
                'anh_poster' => 'phim/venom3.jpg',
                'anh_banner' => 'phim/venom3_banner.jpg',
                'do_tuoi' => 16,
                'danh_gia' => 0,
                'trang_thai' => 'Sắp chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'Deadpool & Wolverine',
                'dao_dien' => 'Shawn Levy',
                'dien_vien' => 'Ryan Reynolds, Hugh Jackman',
                'the_loai' => 'Hành động, Hài',
                'thoi_luong' => 130,
                'ngon_ngu' => 'en',
                'quoc_gia' => 'Mỹ',
                'ngay_khoi_chieu' => '2024-07-26',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Deadpool hợp tác với Wolverine trong cuộc phiêu lưu điên rồ xuyên vũ trụ.',
                'trailer_url' => 'https://www.youtube.com/watch?v=73_1biulkYk',
                'anh_poster' => 'phim/deadpool3.jpg',
                'anh_banner' => 'phim/deadpool3_banner.jpg',
                'do_tuoi' => 18,
                'danh_gia' => 9.3,
                'trang_thai' => 'Đang chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'Avatar 3',
                'dao_dien' => 'James Cameron',
                'dien_vien' => 'Sam Worthington, Zoe Saldaña',
                'the_loai' => 'Phiêu lưu, Viễn tưởng',
                'thoi_luong' => 190,
                'ngon_ngu' => 'en',
                'quoc_gia' => 'Mỹ',
                'ngay_khoi_chieu' => '2025-12-19',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Jake và Neytiri đối mặt với thử thách mới khi Pandora bị xâm lược.',
                'trailer_url' => null,
                'anh_poster' => 'phim/avatar3.jpg',
                'anh_banner' => 'phim/avatar3_banner.jpg',
                'do_tuoi' => 13,
                'danh_gia' => 0,
                'trang_thai' => 'Sắp chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'Despicable Me 4',
                'dao_dien' => 'Chris Renaud',
                'dien_vien' => 'Steve Carell, Kristen Wiig',
                'the_loai' => 'Hoạt hình, Hài hước',
                'thoi_luong' => 95,
                'ngon_ngu' => 'vi-en',
                'quoc_gia' => 'Mỹ',
                'ngay_khoi_chieu' => '2024-07-03',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Gru và gia đình trở lại cùng những chú minion tinh nghịch.',
                'trailer_url' => 'https://www.youtube.com/watch?v=3w4xk3sJgOo',
                'anh_poster' => 'phim/despicableme4.jpg',
                'anh_banner' => 'phim/despicableme4_banner.jpg',
                'do_tuoi' => 6,
                'danh_gia' => 8.1,
                'trang_thai' => 'Đang chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'Fast & Furious 11',
                'dao_dien' => 'Louis Leterrier',
                'dien_vien' => 'Vin Diesel, Michelle Rodriguez',
                'the_loai' => 'Hành động, Đua xe',
                'thoi_luong' => 140,
                'ngon_ngu' => 'en',
                'quoc_gia' => 'Mỹ',
                'ngay_khoi_chieu' => '2025-04-04',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Dom Toretto bước vào hành trình cuối cùng cùng gia đình tốc độ.',
                'trailer_url' => null,
                'anh_poster' => 'phim/fast11.jpg',
                'anh_banner' => 'phim/fast11_banner.jpg',
                'do_tuoi' => 16,
                'danh_gia' => 0,
                'trang_thai' => 'Sắp chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ten_phim' => 'The Batman 2',
                'dao_dien' => 'Matt Reeves',
                'dien_vien' => 'Robert Pattinson, Zoë Kravitz',
                'the_loai' => 'Hành động, Hình sự',
                'thoi_luong' => 150,
                'ngon_ngu' => 'en',
                'quoc_gia' => 'Mỹ',
                'ngay_khoi_chieu' => '2026-10-03',
                'ngay_ket_thuc' => null,
                'tom_tat' => 'Bruce Wayne tiếp tục hành trình chống tội phạm tại Gotham.',
                'trailer_url' => null,
                'anh_poster' => 'phim/batman2.jpg',
                'anh_banner' => 'phim/batman2_banner.jpg',
                'do_tuoi' => 16,
                'danh_gia' => 0,
                'trang_thai' => 'Sắp chiếu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
