<?php
require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

echo "=== Database Statistics Check ===\n";
echo "Date: " . date('Y-m-d H:i:s') . "\n\n";

try {
    $stats = \App\Models\Statistics::all();

    if ($stats->count() > 0) {
        echo "✅ Found " . $stats->count() . " statistics records:\n\n";

        foreach ($stats as $stat) {
            echo "📅 Date: " . $stat->date . "\n";
            echo "💰 Revenue: ₫" . number_format($stat->revenue_today, 0, ',', '.') . "\n";
            echo "🎫 Tickets: " . $stat->tickets_sold_today . "\n";
            echo "👥 Avg Customers: " . $stat->avg_customers_per_store . "\n";
            echo "📈 ROI: " . $stat->campaign_roi . "%\n";
            echo "---\n";
        }
    } else {
        echo "❌ No statistics records found in database\n";
        echo "This means data is being generated by test routes\n";
    }

    echo "\n🔍 Checking today's stats...\n";
    $todayStats = \App\Models\Statistics::getTodayStats();
    echo "Today: " . $todayStats->date . "\n";
    echo "Revenue: ₫" . number_format($todayStats->revenue_today, 0, ',', '.') . "\n";
    echo "Tickets: " . $todayStats->tickets_sold_today . "\n";
    echo "Avg: " . $todayStats->avg_customers_per_store . "\n";
    echo "ROI: " . $todayStats->campaign_roi . "%\n";

} catch (Exception $e) {
    echo "❌ Error: " . $e->getMessage() . "\n";
}

echo "\n=== End Check ===\n";
?>
